apiVersion: v1
kind: Secret
metadata:
  name: ${GITOPS_REPOSITORY_SECRET_NAME}
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: ${GITOPS_APP_OF_APPS_REPO_URL}
