apiVersion: v1
kind: Secret
metadata:
  name: ocpv420-cluster
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: ocpv420
  server: https://api.ocpv420.lab.example.com:6443
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }
