apiVersion: v1
kind: Secret
metadata:
  name: example-cluster
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: example-cluster
  server: https://api.example.invalid:6443
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }
